### ISSUE TITLE
Game is supported but the update is not!

### ISSUE THREAD

**Issue by MangoSlizePro** [Scobalula/Greyhound#13]
Helppp! I can't use Greyhound to extract assets from BO1 because the update isn't supported! Also, could we get tanim_export and xanim_export extension support, please? So I can use CoD-Blender to import xanims. Thanks!

**Comment by Scobalula** [comment]
What region is your game set to in Steam? I need more info, it works fine on my end.

**Comment by MangoSlizePro** [comment]
I'm not sure? My friend from Indonesia gifted it to me so idk if that has anything to do with it?

**Comment by Scobalula** [comment]
You can check in Steam via the Language tab: 
![image](https://user-images.githubusercontent.com/12156105/63937822-40d44a80-ca5b-11e9-9f56-9bcde222b3f6.png)

Also keep in mind modified clients (that includes Game_Mod) are untested and no support is provided for them.

I still need more info, such as what level you're in, etc.
