### ISSUE TITLE
Mesh and bones imported in incorrect positions

### ISSUE THREAD

**Issue by One-Trick-Viper** [Scobalula/Greyhound#16]
Hi there, there is an issue MW 2019's models when imported into a 3D editing software (so far I've tested this on Maya and Blender but I'm sure this is the case for all software out there).

The mesh and bones are imported in incorrect positions

![image](https://user-images.githubusercontent.com/29631812/67639636-762dd500-f8f2-11e9-91ac-03be7275785e.png)

I had this issue with CoD WW2 as well, but it wasn't as bad as it was usually a stock or grip that was misplaced, but with MW 2019 the nearly every part of the model is imported in incorrect positions.

I don't know if this is something fixable by you or if it's simply something to do with how CoD's engine deals with models.

**Comment by Scobalula** [comment]
Invalid issue, as per previous CoDs, "attachments" need to be connected to the joint on the parent model.
