### ISSUE TITLE
No files are exported when exporting files from subdirectories(?)

### ISSUE THREAD

**Issue by x0reaxeax** [Scobalula/Greyhound#21]
Whenever I try exporting files from a `.sabl` or `.sabs` file, no files are exported if those files contain trailing slash i.e. are located in a subdirectory.
I tried:
Checking/Unchecking `Preserve the file paths of sound files` option
Checking/Unchecking `Use SAB Name + Index as name for Black Ops 4 Sound` option
Clearing Cache

No error messages pop up, in fact, Greyhound says all files have been exported successfully.

![screen](https://i.imgur.com/qR7jyQy.jpg)

**Comment by Scobalula** [comment]
It would help a lot if you bothered to provide the name of the file you're loading, otherwise I can't do anything to help you...

**Comment by x0reaxeax** [comment]
Oh shoot, sorry.. The file I'm trying to open is BO4's [`core_frontend.all.sabl`](https://drive.google.com/open?id=15vl3OxUewXwoBOwK96k_E6r_t0BExoPv) , but the issue occurs with every Black Ops 4 `.sabl`/`.sabs` file I extracted with [T8ZoneRipper](https://github.com/Scobalula/T8ZoneRipper) .. I tried extracting those files multiple times to see if they differ in any way, but they don't.

**Comment by Scobalula** [comment]
Thanks, this is now fixed in [1.3.99.0](https://github.com/Scobalula/Greyhound/releases/tag/1.3.99.0), this issue only affected Bo4, which is why I usually ask for exact file names, games, etc.
