### ISSUE TITLE
COD1/UO Support?

### ISSUE THREAD

**Issue by henrikssonkevin** [Scobalula/Greyhound#25]
Hello

Awesome work on this tool. Tried it out on WW2 and it works like a charm. I'm needing something similar to this for COD1/UO and dont really have any personal experience in reverse engineering. Is it something you could do with relative ease or would it require lots of changes?. The only info I have on differences between Version 6 and 5 xmodels stems from this page: https://wiki.zeroy.com/index.php?title=Call_of_Duty:_XMODEL_formats

Thanks for your work again!

**Comment by Scobalula** [comment]
There was some initial work being done on CoD 1/UO/2 here https://github.com/Scobalula/Greyhound/blob/development_v2/src/Greyhound/Greyhound.Logic/Helpers/XModelFileHelper.cs but it's uncertain when I will complete this as I am focusing on other projects now

**Comment by Scobalula** [comment]
If you're able to compile the above projects, I think it should be fine for ripping almost all models including animated ones (excluding viewhands due them being zeroed out) along with textures. Animations are not as tested but I think they should work too.
