### ISSUE TITLE
Greyhound has encountered a fatal error and must close

### ISSUE THREAD

**Issue by MedicFox04** [Scobalula/Greyhound#58]
Ever since a recent update, Greyhound has been experiencing fatal errors when exporting models & opening Xpack files (the files open and the program can view files within, it just tosses the error instantly) from Black Ops 3. It also has the other issues of not exporting image files from Black ops 3 (it says it does, but the exported file(s) are nowhere to be seen) and also not.. seeing any audio files from Black Ops 3, no matter what the "Sound" settings are set to.

Side Note: these issues are spawned from trying to view Workshop files, however these issues weren't problems before

**Comment by dest1yo** [comment]
Could you provide me with the version of Greyhound you used before? It's V.1.23.31.0, right?

**Comment by MedicFox04** [comment]
> Could you provide me with the version of Greyhound you used before? It's V.1.23.31.0, right?

I believe that is the right version in which these issues are non existant, yes. Havn't really kept track of which version i've been using, all i know is that it worked before the new icon change. however for clarification in regards to the program viewing sound files or not, i believe it was a couple more versions prior where it worked, like 1.23.26.0 , although i could be wrong.

Also after some more experimenting, Greyhound (when attempting to Load Game) doesn't register the Steam version of Black Ops Cold War, despite being loaded into a zombies map. the issue could be prevalent with the other steam versions, however i don't have the games to try (mw2019 & vanguard). Greyhound also doesn't view sound files of Infinite Warfare, and when exporting an image.. nothing shows up in the "ximages" folder, just like black ops 3. Greyhound also doesn't view Black Ops 1 sound files... 
I havn't tested all of the CoD games, however these seem to be consistent issues across multiple of the games. It is most likely a safe assumption that these issues purist across all of the games. unless i'm failing to do something on my end...

**Comment by dest1yo** [comment]
I'm not familiar with whether the old CoD extraction of sound worked at all before. I'll investigate and fix the issue when I have time.
For exporting images, this will be solved soon, don't worry

**Comment by MedicFox04** [comment]
> I'm not familiar with whether the old CoD extraction of sound worked at all before. I'll investigate and fix the issue when I have time. For exporting images, this will be solved soon, don't worry. Thank you for your feedback

It was at one point able to extract sound files.. although it only viewed some, not all of the sound files in a given map, but still, it had functioned. just now.. nothing at all.
non the less, of course! thank you for the quick replies, and i hope such issues will be solved without much problems for the many contributors, yes

**Comment by ItsNatoriousB** [comment]
It does not work with the Steam version of BOCW.

**Comment by ItsNatoriousB** [comment]
Does not work with Steam BOCW

> > Could you provide me with the version of Greyhound you used before? It's V.1.23.31.0, right?
> 
> I believe that is the right version in which these issues are non existant, yes. Havn't really kept track of which version i've been using, all i know is that it worked before the new icon change. however for clarification in regards to the program viewing sound files or not, i believe it was a couple more versions prior where it worked, like 1.23.26.0 , although i could be wrong.
> 
> Also after some more experimenting, Greyhound (when attempting to Load Game) doesn't register the Steam version of Black Ops Cold War, despite being loaded into a zombies map. the issue could be prevalent with the other steam versions, however i don't have the games to try (mw2019 & vanguard). Greyhound also doesn't view sound files of Infinite Warfare, and when exporting an image.. nothing shows up in the "ximages" folder, just like black ops 3. Greyhound also doesn't view Black Ops 1 sound files... I havn't tested all of the CoD games, however these seem to be consistent issues across multiple of the games. It is most likely a safe assumption that these issues purist across all of the games. unless i'm failing to do something on my end...

**Comment by MedicFox04** [comment]
sooo after some more fiddling around with exporting files from bo3, it seems to be if the map is loaded it wont export images and crashes when exporting models.. which is odd since the map is needed to be loaded in-order for greyhound to even view the files.
HOWEVER once greyhound loads the files, and the map is unloaded, the exported images will be corrupt (because the map is unloaded) unlike exporting models in such a case which doesn't crash and exports without issue. though Xpack files still crash the program despite files being loaded into greyhound.

P.S. these issues stem from workshop maps.. which have no issues in exporting sounds from

**Comment by dest1yo** [comment]
> sooo after some more fiddling around with exporting files from bo3, it seems to be if the map is loaded it wont export images and crashes when exporting models.. which is odd since the map is needed to be loaded in-order for greyhound to even view the files. HOWEVER once greyhound loads the files, and the map is unloaded, the exported images will be corrupt (because the map is unloaded) unlike exporting models in such a case which doesn't crash and exports without issue. though Xpack files still crash the program despite files being loaded into greyhound.
> 
> P.S. these issues stem from workshop maps.. which have no issues in exporting sounds from

This issue will be resolved in the next update

**Comment by dest1yo** [comment]
https://github.com/Scobalula/Greyhound/releases/tag/1.46.2.0

**Comment by dest1yo** [comment]
Issues with sound export remain to be investigated

**Comment by qq1295887657** [comment]
you need to put it in full-english path
