### ISSUE TITLE
Greyhound Crashes While Attempting to Export Hashed Xanim Files From Warzone

### ISSUE THREAD

**Issue by evantyler223** [Scobalula/Greyhound#59]
As stated above, Greyhound crashes when exporting certain animation files with names like "Xanim_(random letters & numbers)". It is difficult to tell which animation files in particular, since it crashes, but I will include both screenshots of the crash and the crash_dump. I tried to solve the issue by downloading the newest version of Greyhound but the error persisted.
![image](https://github.com/Scobalula/Greyhound/assets/147236528/dab4326b-154a-4773-bac7-26ff27f65d48)
![image2](https://github.com/Scobalula/Greyhound/assets/147236528/5ebcac65-2452-41ed-82a4-6e7028892192)

**Comment by dest1yo** [comment]
You should be able to see the last exported file name in the log. Is the game you are extracting mw6?

**Comment by dest1yo** [comment]
https://github.com/Scobalula/Greyhound/releases/tag/1.46.2.0
