### ISSUE TITLE
BO4 missing meshes on all torso and leg model exports

### ISSUE THREAD

**Issue by xCortlandx** [Scobalula/Greyhound#6]
Previous build worked fine,

Already opened bug in Discord but you guys were all sensitive and couldn't understand what I meant and kicked me, bug still remains though.

**Comment by Scobalula** [comment]
For context, not sensitive, asked several times for specific model names, provided generic lists. I cannot fix issues without specific samples, giving me a list means nothing as I do not have the time to start ripping multiple items to find what "might" be the issue. Chat goes further on with same request for specific names from another person. Issue will remain open as the issue still needs to be addressed, but the issue of specific model names being required still needs to be addressed as well

![](https://i.imgur.com/sUNZ47U.png)

**Comment by xCortlandx** [comment]
Ye maybe you forgot the image i posted with the models that were affected

**Comment by Scobalula** [comment]
Your screenshot was a generic list from the tool, issue closed as I've identified the issue by people able to provide me with literal model names.

**Comment by 762NATO** [comment]
what a unit
