### ISSUE TITLE
Greyhound crashes when exporting models as xmodel_export.

### ISSUE THREAD

**Issue by WECoyote99** [Scobalula/Greyhound#60]
So I am redoing my blood of the dead zombie models and any time I try to export them, greyhound crashes mid export and closes. Does it have to do with the models itself or is it the app?

**Comment by dest1yo** [comment]
No one knows what game and model you are exporting.

**Comment by WECoyote99** [comment]
I stated it was Blood of the Dead from Black ops 4

**Comment by dest1yo** [comment]
:( model name

**Comment by ItsNatoriousB** [comment]
Which version of GH?

**Comment by WECoyote99** [comment]
> Which version of GH?

Most recent update since scob stopped

**Comment by WECoyote99** [comment]
> :( model name

c_t8_zmb_mob_zombie_ ones (excluding Brutus, ghosts, hellhound and the player models)

**Comment by dest1yo** [comment]
https://github.com/Scobalula/Greyhound/releases/tag/1.46.2.0
