### ISSUE TITLE
Greyhound - Add New Feature for LODs on Treyarch Games

### ISSUE THREAD

**Issue by JaguarPlays** [Scobalula/Greyhound#62]
So there's only 2 ways to export models.
Only have LOD0 or export all LODS.

If you're doing hashed models in Cold War or Black Ops 4, you will have to export all models with all LODS.
It would be great to have a system or option that it only exports the Highest LOD available. Since Treyarch Games the highest LOD is the highest quality one.

**Comment by dest1yo** [comment]
https://github.com/Scobalula/Greyhound/releases/tag/1.46.2.0
