### ISSUE TITLE
Cod Game not recognised

### ISSUE THREAD

**Issue by RumblyStumbly** [Scobalula/Greyhound#63]
This is on Black Ops Cold War and Black Ops 4, i re-installed the game from bnet and still won't recognize, rarely it would work but not all assets come out.
![ghe](https://github.com/Scobalula/Greyhound/assets/156553953/fb590e92-6884-40f1-b5e8-2f7ff94cc74a)

**Comment by dest1yo** [comment]
You need to make sure you are running the software in administrator mode

**Comment by RumblyStumbly** [comment]
I have tried that too. Still would not recognize.

**Comment by dest1yo** [comment]
Are you using the latest version of Greyhound? It's 1.46.2.0

**Comment by RumblyStumbly** [comment]
Yes i am its the screenshot shown.

**Comment by dest1yo** [comment]
The basic functionality of this query process has not changed for a long time and has been extensively tested before.
I think there is a high probability that it is a problem with your system.
Have you tried extracting other COD games?

**Comment by RumblyStumbly** [comment]
I have tried MW and Vanguard they work, BO4 and BOCW only have this issue.

**Comment by dest1yo** [comment]
Thanks for the feedback. I will use it as a reference. The main thing is that I cannot reproduce this problem. If there is other information, I will take a look.

**Comment by subzerohurley** [comment]
Wanted to chip in, While running the game in Administrator did fix the original "Not support" issue, there's a new one. 
"Game IS supported, but not this update, please wait for upcoming patch for support"

**Comment by dest1yo** [comment]
> Wanted to chip in, While running the game in Administrator did fix the original "Not support" issue, there's a new one. "Game IS supported, but not this update, please wait for upcoming patch for support"

One thing you need to make sure is that you are not using an a pirated game.

**Comment by subzerohurley** [comment]
> > Wanted to chip in, While running the game in Administrator did fix the original "Not support" issue, there's a new one. "Game IS supported, but not this update, please wait for upcoming patch for support"
> 
> One thing you need to make sure is that you are not using a pirated game.

I'm not, there was a cold war update from what I understand
![image](https://github.com/Scobalula/Greyhound/assets/18029175/83f307fc-e1ee-4269-b721-ee158789bd30)
