### ISSUE TITLE
Greyhound doesn't show every xmodel in the game cod4

### ISSUE THREAD

**Issue by PrawyCoD1** [Scobalula/Greyhound#65]
For example in raw folder there are some acog xmodels that are not present in greyhound

![image](https://github.com/Scobalula/Greyhound/assets/70172890/f208f0ff-c923-4435-9d03-d5fce0e23b4f)
![image](https://github.com/Scobalula/Greyhound/assets/70172890/e1ecb9e9-7b08-4015-a521-34a72870285e)

**Comment by mrpsycho-ve** [comment]
maybe because theyre not loaded? greyhound only shows the models that are loaded so you have to at least be holding that model in your hands so the game loads it and greyhound will show them, they might even be unused models that aren't even used ingame

**Comment by PrawyCoD1** [comment]
> maybe because theyre not loaded? greyhound only shows the models that are loaded so you have to at least be holding that model in your hands so the game loads it and greyhound will show them, they might even be unused models that aren't even used ingame

Okay let's say it's not used but maybe I want to use the model why I don't have that option?

**Comment by mrpsycho-ve** [comment]
like i just said, if its not loaded in the current level, it will not show up on the list for you to export.

if you need to export models from the modtools into like maya format or something just use tom xmodelutils https://tom-crowley.co.uk/downloads

**Comment by dest1yo** [comment]
> like i just said, if its not loaded in the current level, it will not show up on the list for you to export.
> 
> if you need to export models from the modtools into like maya format or something just use tom xmodelutils https://tom-crowley.co.uk/downloads

correct answer
