### ISSUE TITLE
Does this works with Call of Duty 1?

### ISSUE THREAD

**Issue by AverageMannco** [Scobalula/Greyhound#68]
Im just curious because i want to rip the bomber models from UO

**Comment by dest1yo** [comment]
Unfortunately, it is not supported

**Comment by AverageMannco** [comment]
> Unfortunately, it is not supported

Thanks

**Comment by PrawyCoD1** [comment]
> Im just curious because i want to rip the bomber models from UO

you can just open .pk3 file and get your xmodel
