### ISSUE TITLE
Not exporting texture images, with the models

### ISSUE THREAD

**Issue by pyrobaby** [Scobalula/Greyhound#72]
to expand on the title, I tried to export a few model tonight and none of them exported with their texture image's, I have text [ .txt ] files for the images that should of exported with the model. 

I do know that there is a chance that this is do to CoD:MW3 [ which is where I got the model from ] just dropping season three.

![image](https://github.com/Scobalula/Greyhound/assets/166001248/64c59db5-5d98-4a68-bdb6-d75436804d98)
![image](https://github.com/Scobalula/Greyhound/assets/166001248/e906475d-cbd8-4de2-96a9-69adbcd5c122)
![image](https://github.com/Scobalula/Greyhound/assets/166001248/b86c3350-1bba-420c-aa6b-3cfe2a8a473f)

**Comment by dest1yo** [comment]
https://github.com/Scobalula/Greyhound/releases/tag/1.46.3.2

**Comment by dest1yo** [comment]
I just saw this ask. If you missed the update you can check here.
https://github.com/Scobalula/Greyhound/releases/tag/1.46.3.2
