### ISSUE TITLE
Cod Vanguard assets are not loading

### ISSUE THREAD

**Issue by Momo1944-45** [Scobalula/Greyhound#73]
i was launching Cod Vanguard because i wanted to get out some textrues out but when i click Load game it would say
"no instances of supported game where found (and i launched vanguard for this btw and in a mission) so if anyone knows how to fix this please reply

**Comment by dest1yo** [comment]
For titles using Ricochet, [Cordycep](https://github.com/Scobalula/Cordycep) must be used to extract assets.
