### ISSUE TITLE
[Feature request] Extract CSVs and other script files from Call of Duty : Modern Warfare 2 (2009)

### ISSUE THREAD

**Issue by mrmaller1905** [Scobalula/Greyhound#74]
Can you add support for dumping localized strings or other scripts from Call of Duty : Modern Warfare 2 (2009)?

**Comment by dest1yo** [comment]
Use https://github.com/EthanC/Jekyll

**Comment by mrmaller1905** [comment]
> Use https://github.com/EthanC/Jekyll

I get an error log:
1>------ Build started: Project: PhilLibX, Configuration: Debug Any CPU ------
1>C:\Users\PC\Source\Repos\Jekyll\PhilLibX\IO\ProcessReader.cs(193,32,193,42): error CS0103: The name 'Decryption' does not exist in the current context
1>Done building project "PhilLibX.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
