### ISSUE TITLE
MW2 (iw4x) Not detecting

### ISSUE THREAD

**Issue by Umarsubs** [Scobalula/Greyhound#79]

**Comment by dest1yo** [comment]
Unfortunately unofficial version is not the scope of greyhound

**Comment by Umarsubs** [comment]
@dest1yo So it cant be fixed?

**Comment by cf** [comment]
open up the Greyhound.exe in a Hex Editor and replace these byte combinations to update the pointer offsets:

D0816F00 -> A8987900
087F6F00 -> E8957900
009F6F00 -> D8937900

should be good after that

**Comment by cf** [comment]
actually for the strings table/3rd one, it is offset=*((uint32_t *)0x01dc2200), and for me this is 0x01D00100

so replace:
009F6F00 -> 0001D001

but where it allocates *might* be dynamic (haven't bothered reversing further), but you can always grab the pointer in cheat engine
