### ISSUE TITLE
New BO4 hashes by Planet and The Jaguar plays

### ISSUE THREAD

**Issue by RealPlanet** [Scobalula/Greyhound#8]
ee4e857c529b4cc,p8_zom_chaos_mysterybox
9af0ce07aab606c,p8_zom_chaos_mysterybox_away
e6ffc5b7e43c1cc,p8_zom_chaos_mysterybox_idle
f7451488d425f6f,p8_zom_chaos_perkmachine_danu
431b975606b92e1,p8_zom_chaos_perkmachine_odin
1784490f7db2a70,p8_zom_chaos_perkmachine_zeus
1eece3c5d5dbbd4,p8_zom_chaos_perkmachine_ra
efdd19dfd268f23,p8_zom_chaos_pack_a_punch
10e699507e56268,p8_zom_chaos_pack_a_punch_spawn_model
789c7eb67d57a48,p8_zom_global_elixir_bottle_04
59641755dd964f8,p8_zom_global_elixir_bottle_05
45b7a2ec878edca,p8_zom_global_elixir_bottle_06
4320bbf0d0d8be7,p8_zom_global_elixir_bottle_07
29e1fb58a0f84ef,p8_zom_global_elixir_bottle_09
16bd3daacb2521f,p8_zom_chaos_perk_mule_kick_world
bb131e818b68032,p8_zom_chaos_perk_mule_kick_view
c8ec276d5ec71c,p8_zom_chaos_perk_staminup_view
5e370475fe5bdc9,p8_zom_chaos_perk_staminup_world
d63827526510e2f,p8_zom_chaos_perk_deadshot_dealer_world
7aacc25f361b0e2,p8_zom_chaos_perk_deadshot_dealer_view
dcbde11430ba19c,p8_zom_chaos_perk_death_perception_world
af9235d5ba511f7,p8_zom_chaos_perk_death_perception_view
d65e408dce5970d,p8_zom_chaos_perk_phd_slider_world
633fc1a804e25b0,p8_zom_chaos_perk_phd_slider_view
ec0e3d60c3ddf98,p8_zom_chaos_perk_zombshell_view
76b99e765194955,p8_zom_chaos_perk_zombshell_world
d89b20692bd6148,p8_zom_chaos_perk_bandolier_bandit_world
b738430be64517b,p8_zom_chaos_perk_winters_wail_world
6a819a6d297514e,p8_zom_chaos_perk_winters_wail_view
a79c2a84e9e315d,p8_zom_chaos_perk_ethereal_razor_view
ab0c97c0495b86d,p8_zom_chaos_perk_quick_revive_view
93c4245074d0fba,p8_zom_chaos_perk_quick_revive_world
aa56fd357cd50e,p8_zom_chaos_perk_stone_cold_stronghold_world
66aa9d5261924d1,p8_zom_chaos_perk_stone_cold_stronghold_view
a13539f4a132cdb,p8_zom_chaos_perk_electric_burst_world
22f327941d2fb2e,p8_zom_chaos_perk_electric_burst_view
897379b2b2e1e4b,p8_zom_chaos_perk_timeslip_word
37eedc7f879607a,p8_zom_chaos_perk_dying_wish_world
ffdfb2ec849f940,p8_col_plank_wood_board_splintered_01
feb0d9324b26bee,p8_fxp_zm_red_mq_perseus_shield_tendril
fe01649894a9bb6,p8_food_fruit_watermelon_pile_01
fe567e61b3e42dd,p8_zm_red_temple_apollo_architrave_02_corner_lt_176a
fe75be16e47231,p7_foliage_distictis_hanging_ledge_128_long
fe26c4f6624b4e1,collision_gen_128x128x128
fd66c1355671b3b,p8_zom_aether_perk_bottle_10
fd05db60d5d97ab,p7_foliage_bush_sakaki_thick_01_flower
fcf1053561d4c6,c_zom_chaos_blightfather_body
fc271ff96d2e162,p8_ice_large_rock_01
1a3bb06bdf52857,p8_zom_global_brick_wall_corner_00
1a411dafa5678e2,p8_zom_red_rune_circle_hemera
1a636c7c776b5b4,p8_fxp_fluid_spill_2
1ac858f66150f13,p8_zom_red_treasury_boeotians_lintel_01
1b7c2589578a232,p7_foliage_distictis_hanging_ledge_128
1b27ead7a63a4f0,p8_fxp_fluid_splash_hirez_00
1b0280145e76c57,p7_ra2_wall_fountain_lion
1cd4818bd34691,p7_foliage_distictis_hanging_ledge_32_long
fc6c363836c5621,p7_foliage_flower_bougainvillea_bushyvarient
fc3c538c03753c4,p8_zom_red_dks_chaos_crystal_support_single_01a
fbcb938c03120b2,p8_zom_red_dks_chaos_crystal_support_single_03a
fb62a39fad3c071,p8_fxp_fluid_tendril_1
fb9d538c02f1a6f,p8_zom_red_dks_chaos_crystal_support_single_02a
fb2c938c028e75d,p8_zom_red_dks_chaos_crystal_support_single_04a
1e930dec9b38cee,p8_foliage_weeds_tall_straight_8
1e5318a4cb4eeb4,foliage_flower_lantana_montevidensis_med
1ebac9cb464b2c9,p7_ban_foliage_bush_ground_01
1f6b2fea098d27b,p8_fxp_fluid_splash_hirez_01
1f8e3acfc3704c8,p8_zom_red_temple_apollo_architrave_03_corner_rt_24a
1f95b097cbb12c3,p8_zom_ae_tribute_holder
2a5de483eb7cd51,p8_wz_foliage_wild_grass_128_short
2a066d349ea2d20,p7_candle_med_melt
2a355ea5ba1edd2,p7_foliage_distictis_hanging_ledge_192_long
2a954306f4040f4,wpn_t8_dragon_and_viper_level3_view

**Comment by Scobalula** [comment]
Please file issues to the Index repo in the future
