### ISSUE TITLE
hi, so i have an issue. it says this issue, "This game is supported, but the current update is not. Please wait for an upcoming patch for support". How do i fix this issue? i already redownloaded the game. uninstalled grey hound but i keep getting this issue... PLEASE HELP

### ISSUE THREAD

**Issue by zxelo** [Scobalula/Greyhound#9]

**Comment by EthanC** [comment]
The error message very clearly states what the issue is, you cannot resolve it at this time.

Please stop opening [issues](https://github.com/Scobalula/GreyhoundPackageIndex/issues/7) for this.

**Comment by zxelo** [comment]
I don’t get it, do I have to wait till u guys update it

**Comment by EthanC** [comment]
> This game is supported, but the current update is not. **Please wait for an upcoming patch for support.**

**Comment by zxelo** [comment]
Ok so it’s on your part? Or mine
